### ISSUE TITLE
IBM igc trial not opening in windows 8. After installing only a white page is opening. 

### ISSUE THREAD

**Issue by Nikita1409** [ibm-uglab/IGC-trial#8]

**Comment by sachethegde** [comment]
@Nikita1409 Did you see a white page when you launched the Trial app or when you launched the IGC console on the 4th page?

Can you please send the log file to "sachet.hegde@ibm.com" ? So that I can identify the problem and get back.

Log file location is, %USERPROFILE%\AppData\Roaming\IGC\log.log
(AppData folder is a hidden folder)

Thanks,

**Comment by sachethegde** [comment]
@Nikita1409 Unfortunately we do not support windows-8 at this point of time. 

Thanks,
Sachet
